//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjSmartDia {
    
    
    public partial class wfDiagnosis {
        
        /// <summary>
        /// BannerDiagnosis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::prjSmartDia.UserControls.BannerDiagnosis BannerDiagnosis;
        
        /// <summary>
        /// Diagnosis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::prjSmartDia.UserControls.Diagnosis Diagnosis;
        
        /// <summary>
        /// Diagnosisimage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::prjSmartDia.UserControls.Diagnosisimage Diagnosisimage;
    }
}
